jobs:
  - job: Fedora_28
    pool:
      vmImage: 'ubuntu-16.04'

    steps:
    - script: docker-compose up -d fedora
      displayName: 'Testing dotfiles...'

  - job: Ubuntu_1804
    pool:
      vmImage: 'ubuntu-16.04'

    steps:
    - script: docker-compose up -d ubuntu
      displayName: 'Testing dotfiles...'

  - job: macOS
    pool:
      vmImage: 'macOS-10.13'

    steps:
    - script: ./install.sh --accept-mscorefonts-eula --quiet --log-path=/dev/stdout
      displayName: 'Testing dotfiles...'
